# generated by add-option
# Fri Sep 16 08:04:55 PDT 2011
#
#/ usage: stubbs:archive --file|-f <> [--modules|-m <>] --version|-v <>

# print USAGE and exit
rerun_option_usage() {
    grep '^#/ usage:' <"$0" | cut -c4- >&2
    return 2
}

# print USAGE and exit
rerun_option_error() {
    if [[ "$RERUN_COLOR" == "true" ]]
    then echo -e ${red}"SYNTAX: $*"${_red} >&2 
    else echo "SYNTAX: $*" >&2
    fi
    exit 2
}


# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_error
}

# options: [file modules version]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        -f|--file) rerun_option_check $# ; FILE=$2 ; shift ;;
        -m|--modules) rerun_option_check $# ; MODULES=$2 ; shift ;;
        -v|--version) rerun_option_check $# ; VERSION=$2 ; shift ;;
        # unknown option
        -?)
            rerun_option_usage
            exit 2
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$MODULES" ] && MODULES="*"
