.TH stubbs 1 "Sun Oct 14 12:07:41 ADT 2012" "Version 1" "Rerun User Manual" 
.SH NAME
stubbs \- "Simple rerun module builder"
.PP
.SH SYNOPSIS
.PP
\f[CR] 
rerun [ARGS] stubbs: [ add-command | add-module | add-option | archive | docs | edit | rm-option | test ] [OPTIONS]
\f[]
.SH COMMANDS
.SH stubbs:add-command \f[]--command <> --desc <> --module <> --overwrite <false> --template <$RERUN_MODULES/stubbs/templates/default.sh>
"add command to module"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--command \f[]"the command name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--desc \f[]"the command description"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--overwrite \f[]"overwrite the command default.sh (true|false)"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]false\f[]
.RS
.RE
.TP
.B \--template \f[]"default script template"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]$RERUN_MODULES/stubbs/templates/default.sh\f[]
.RS
.RE
.SH stubbs:add-module \f[]--description <> --module <>
"add a new module"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--description \f[]"the module description"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:add-option \f[][--arg <false>] --command <> [--default <>] --desc <> [--long <>] --module <> --option <> [--range <"*">] [--required <false>] [--short <>]
"add a command option"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--arg \f[]"option takes argument (true|false)"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]false\f[]
.RS
.RE
.TP
.B \--command \f[]"the command name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--default \f[]"default value"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--desc \f[]"the option description"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--long \f[]"long option name"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--option \f[]"the option name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--range \f[]"argument value range"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]"*"\f[]
.RS
.RE
.TP
.B \--required \f[]"required option (true|false)"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]false\f[]
.RS
.RE
.TP
.B \--short \f[]"short option name"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:archive \f[][--file <>] --modules <"*"> [--version <>]
"build a self extracting rerun" 
.PP
\f[I]OPTIONS\f[]
.TP
.B \--file \f[]"self extracting archive file"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--modules \f[]"modules glob pattern"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]"*"\f[]
.RS
.RE
.TP
.B \--version \f[]"the archive version"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:docs \f[][--file <"$RERUN_MODULES/$MODULE/${MODULE}.1">] --module <>
"generate the docs"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--file \f[]"file name"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]"$RERUN_MODULES/$MODULE/${MODULE}.1"\f[]
.RS
.RE
.TP
.B \--module \f[]"module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:edit \f[]--command <> --module <>
"edit a command script"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--command \f[]"the command name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:rm-option \f[]--command <> --module <> --option <>
"remove a command option"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--command \f[]"the command name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--option \f[]"the option name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:test \f[][--logs <>] --module <> [--plan <>]
"run module test scripts"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--logs \f[]"logs directory"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--plan \f[]"the test plan"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH RETURN VALUES
.PP
Successful completion: 0
.SH AUTHORS
alexh
.SH "SEE ALSO"
rerun
.SH KEYWORDS
stubbs
