.TH stubbs 1 "Thu Nov 22 11:28:34 PST 2012" "Version 1" "Rerun User Manual" 
.SH NAME
stubbs \- "Simple rerun module builder"
.PP
.SH SYNOPSIS
.PP
\f[CR] 
rerun [ARGS] stubbs: [ add-command | add-module | add-option | archive | docs | edit | migrate | rm-option | test ] [OPTIONS]
\f[]
.SH COMMANDS
.SH stubbs:add-command \f[]
"add command to module"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--command \f[]"the command name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--description \f[]"the module description"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--overwrite \f[]"overwrite the command default (true|false)"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]false\f[]
.RS
.RE
.SH stubbs:add-module \f[]
"add a new module"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--description \f[]"the module description"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--interpreter \f[]\f[]
required: \f[I]\f[] ,
arguments: \f[I]\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:add-option \f[]
"add a command option"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--arg \f[]"option takes argument (true|false)"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]false\f[]
.RS
.RE
.TP
.B \--command \f[]"the command name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--default \f[]"default value"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--description \f[]"the module description"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--export \f[]"export option variable (true|false)"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]false\f[]
.RS
.RE
.TP
.B \--long \f[]"long option name"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--option \f[]"the option name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--range \f[]"argument value range"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]"*"\f[]
.RS
.RE
.TP
.B \--required \f[]"required option (true|false)"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]false\f[]
.RS
.RE
.TP
.B \--short \f[]"short option name"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:archive \f[]
"build a self extracting rerun" 
.PP
\f[I]OPTIONS\f[]
.TP
.B \--file \f[]"self extracting archive file"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--format \f[]"Specify the format of the archive(s) to build"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]bin\f[]
.RS
.RE
.TP
.B \--modules \f[]"modules glob pattern"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]"*"\f[]
.RS
.RE
.TP
.B \--release \f[]"Specify the release number of the archive"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
, default: \f[I]1\f[]
.RS
.RE
.TP
.B \--version \f[]"the archive version"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:docs \f[]
"generate the docs"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--file \f[]"self extracting archive file"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:edit \f[]
"edit a command script"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--command \f[]"the command name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:migrate \f[]
"Migrate 0.9 modules to the 1.0 module format"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:rm-option \f[]
"remove a command option"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--command \f[]"the command name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--option \f[]"the option name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH stubbs:test \f[]
"run module test scripts"
.PP
\f[I]OPTIONS\f[]
.TP
.B \--answers \f[]"option answer file"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--logs \f[]"logs directory"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--module \f[]"the module name"\f[]
required: \f[I]true\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.TP
.B \--plan \f[]"the test plan"\f[]
required: \f[I]false\f[] ,
arguments: \f[I]true\f[]
.RS
.RE
.SH RETURN VALUES
.PP
Successful completion: 0
.SH AUTHORS
alexh
.SH "SEE ALSO"
rerun
.SH KEYWORDS
stubbs
