#!/usr/bin/env bash
#
#/ command: @MODULE@:@NAME@: "@DESCRIPTION@"
#
#/ usage: rerun @MODULE@:@NAME@ [options]
#
#/ rerun variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: @VARIABLES@

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library" ; exit 1 ; 
}

# Parse the command options.
[ -r $RERUN_MODULE_DIR/commands/@NAME@/options.sh ] && {
  . $RERUN_MODULE_DIR/commands/@NAME@/options.sh || exit 2 ;
}

# Exit immediately upon non-zero exit for simple commands. 
# See [set](http://ss64.com/bash/set.html)
# Pipelines return with exit code of left most command failure.
# See [pipelines](http://www.gnu.org/software/bash/manual/bash.html#Pipelines)
set -e -o pipefail


# ------------------------------
# Your implementation goes here.
# ------------------------------

exit $?

# Done
