#!/bin/bash
#
# NAME
#
#   add-module
#
# DESCRIPTION
#
#   add a new module
#

# Source common function library
source $RERUN_MODULES/stubbs/lib/functions.sh || { echo "failed laoding function library" ; exit 1 ; }

rerun_init

# Get the options
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        # options without arguments
	# options with arguments
	-m|--name)
	    rerun_option_check "$#"
	    NAME="$2"
	    shift
	    ;;
	--description)
	    rerun_option_check "$#"
	    DESC="$2"
	    shift
	    ;;
        # unknown option
	-?)
	    rerun_option_error
	    ;;
	  # end of options, just arguments left
	*)
	    break
    esac
    shift
done

# Post processes the options
[ -z "$NAME" ] && {
    echo "Module name: "
    read NAME
}

[ -z "$DESC" ] && {
    echo "Module description: "
    read DESC
}

# Create module structure
mkdir -p $RERUN_MODULES/$NAME || rerun_die
# Create etc/ subdirectory
mkdir -p $RERUN_MODULES/$NAME/etc || rerun_die
# Create commands/ subdirectory
mkdir -p $RERUN_MODULES/$NAME/commands || rerun_die

# Generate a profile for metadata
(
cat <<EOF
# generated by stubbs:add-module
# $(date)
NAME=$NAME
DESCRIPTION="$DESC"

EOF
) > $RERUN_MODULES/$NAME/metadata || rerun_die

# Copy a basic function library
mkdir -p $RERUN_MODULES/$NAME/lib || rerun_die
sed 's/@MODULE@/$NAME/g' $RERUN_MODULES/stubbs/templates/functions.sh \
   > $RERUN_MODULES/$NAME/lib/functions.sh || rerun_die

# Done
echo "Created module structure: $RERUN_MODULES/$NAME"
