#!/bin/bash

EXEC_DIR=$(dirname $(dirname $0))
echo $EXEC_DIR
# Source common function library
. $RERUN_MODULES/stubbs/lib/command.sh

rerun_init

# Get the options
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        # options without arguments
	# options with arguments
	-name)
	    arg_syntax_check "$#"
	    NAME="$2"
	    shift
	    ;;
	-description)
	    arg_syntax_check "$#"
	    DESC="$2"
	    shift
	    ;;
        # unknown option
	-?)
	    syntax_error
	    ;;
	  # end of options, just arguments left
	*)
	    break
    esac
    shift
done

# Post processes the options
[ -z "$NAME" ] && {
    echo "Module name: "
    read NAME
}

[ -z "$DESC" ] && {
    echo "Module description: "
    read DESC
}

# Create module structure
mkdir -p $RERUN_MODULES/$NAME || error 
# Create etc/ subdirectory
mkdir -p $RERUN_MODULES/$NAME/etc || error
# Create commands/ subdirectory
mkdir -p $RERUN_MODULES/$NAME/commands || error

# Generate a profile for metadata
(
cat <<EOF
# generated by add-module
# $(date)
NAME=$NAME
DESCRIPTION="$DESC"

EOF
) > $RERUN_MODULES/$NAME/metadata || error


# Done
echo "Created module structure: $RERUN_MODULES/$NAME"
