#!/usr/bin/env bash
#
# @FILE@ - This is a self extracting archive. 
#
#
# generator: @GENERATOR@
# decoder: @DECODER@
# date: @DATE@
# user: @USER@
# archive-version: @VERSION@
# archive-release: @RELEASE@
#/ usage: @FILE@ [--archive-version-release] [--extract-only|-N <>] [--extract-dir|-D <>] [module]:[command] [options]


# Function to print error message and exit.
die() { echo >&2 "ERROR: $* " ; exit 1 ; }
# 
usage() { grep '^#/ usage:' <"$0" | cut -c4- >&2 ; }
cleanup() {
    for f in ${SCRATCH_FILES[*]}
    do  rm -rf $f
    done
}


case "$1" in
    --archive-version-release)
        vers=$(grep "^# archive-version:" $0|cut -f3 -d" ")
        rel=$(grep  "^# archive-release:" $0|cut -f3 -d" ")
        echo >&2 "${vers}-${rel}"
        exit 0 ;
        ;;
    --extract-only|-N) [ -z "$2" ] && { usage ; exit 2 ; }
        EXTRACT_ONLY=true
        EXTRACT_DIR=$2
        shift;
        ;;
    --extract-dir|-D) [ -z "$2" ] && { usage ; exit 2 ; }
        EXTRACT_DIR=$2
        shift; shift;
        ;;
esac

trap "{ cleanup ; }" EXIT

: ${TMPDIR:=/tmp}
declare -a SCRATCH_FILES=()

umask 0002

# EXTRACT_DIR is the directory where files are extracted.
# If it is unset, create a temporary directory.
if [[ -z "${EXTRACT_DIR}" ]]
then
    SCRATCH_FILES[0]=$(mktemp -d ${TMPDIR}/rerun.bin.XXXXXX) || die "failed creating temporary directory."
    EXTRACT_DIR=${SCRATCH_FILES[0]}
else
    mkdir -p "$EXTRACT_DIR"
fi
export PAYLOAD=${EXTRACT_DIR}

# CWD is passed to launcher as an environment variable.

export CWD=$(pwd)

# Extraction time!
# - read lines from delimiter and pass to tar unarchive
cat $0                            | 
sed -e '1,/^__ARCHIVE_BELOW__/ d' | 
@DECODER@                         | 
(cd $EXTRACT_DIR && tar xzf -) || die "Failed unarchiving $0."

#
# Exit, if the --extract-only flag was set.
#
if [[ -n "$EXTRACT_ONLY" ]]
then exit $? 
fi

#
# Run the launcher !
#
bash $EXTRACT_DIR/launcher "$@"
RETVAL=$?


# Stop this script from executing before we reach the binary archive!
exit ${RETVAL:=0}

__ARCHIVE_BELOW__
