#!/bin/bash
#
# extract - this is a self contained self extracting rerun 
#
# generator: @GENERATOR@
# date: @DATE@
# user: @USER@

# Function to print error message and exit
die() { echo "ERROR: $* " ; exit 1 ; }

umask 0002

# extracted payload goes in here
export PAYLOAD=`mktemp -d /tmp/rerun.bin.XXXXXX` || die "failed making payload extraction directory"

SIZE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0` || die "error sizing payload content"

# Extraction time!
# - read lines from delimiter and pass to tar unarchive
tail -n+$SIZE $0 | (cd $PAYLOAD && tar xzf -) || die "unarchiving failed. (tar=$(which tar). size=$SIZE)"

# CWD and TMDIR are passed to launcher as env variables
export CWD=/tmp
export PAYLOAD

# Change directory to the temp directory
cd $PAYLOAD || die

# Run the launcher !
bash ./launcher $*
RETVAL=$?

# Go back to original working directory
cd $CWD

# Clean up after ourselves
rm -rf $PAYLOAD

# Stop this script from executing before we reach the binary archive!
exit ${RETVAL:=0}

__ARCHIVE_BELOW__
