#!/bin/bash
#
# Launches rerun from an self extracting archive script
#

# Function to print error message and exit
die() { echo "ERROR: $* " ; exit 1 ; }

# Check for required environment variables 
[ -z "${CWD}" ] && die "CWD not set" ;# current working directory
[ -z "${TMPDIR}" ] && die "TMPDIR not set" ;# archive artifacts 

# Verify the extracted artifact contents
[ -d ./rerun ] || die "rerun subdirectory not found"
[ -d ./rerun/modules ] || die "missing modules subdirectory"
[ -f ./rerun/rerun ] || die "missing rerun script"
[ -x ./rerun/rerun ] || { chmod +x ./rerun || die "couldn't set rerun executable" ; }

# set the module directory base
export RERUN_MODULES=$TMPDIR/rerun/modules

# move into the current working directory
cd $CWD || die "couldn't change to cwd: $CWD"

# launch it!
exec $TMPDIR/rerun/rerun $*

# Done