#!/usr/bin/env bash
#
# launcher - Launch rerun from an self extracting archive script
#
# generator: @GENERATOR@
# date: @DATE@
# user: @USER@
# archive-version: @VERSION@
# archive-release: @RELEASE@

# Function to print error message and exit
die() { echo "ERROR: $* " >&2 ; exit 1 ; }

# Check for required environment variables 
[ -z "${CWD}" ] && die "CWD not set" ;# user's current working directory
[ -z "${PAYLOAD}" ] && die "PAYLOAD not set" ;# archive artifacts 

# Verify the extracted artifact contents
[ -d ./rerun ] || die "rerun subdirectory not found"
[ -d ./rerun/modules ] || die "missing modules subdirectory"
[ -f ./rerun/rerun ] || die "missing rerun script"
[ -x ./rerun/rerun ] || { chmod +x ./rerun || die "couldn't set rerun executable" ; }

# set the module directory base
export RERUN_MODULES=$PAYLOAD/rerun/modules

# move into the current working directory
cd $CWD || die "couldn't change to current working directory: $CWD"

# add archive rerun script to path
PATH=$PATH:$PAYLOAD/rerun

# launch it!
exec $PAYLOAD/rerun/rerun "$@"

# Done
