# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Wed Sep 27 23:06:25 CDT 2017
#
#/ usage: stubbs:add-option [ --arg <false>]  --command|-c <> [ --default|-d <>]  --description <> [ --export <false>] [ --long <>]  --module|-m <>  --option|-o <> [ --required <false>] [ --short <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --arg) rerun_option_check $# $1; ARG=$2 ; shift ;;
            --command|-c) rerun_option_check $# $1; COMMAND=$2 ; shift ;;
            --default|-d) rerun_option_check $# $1; DEFAULT=$2 ; shift ;;
            --description) rerun_option_check $# $1; DESCRIPTION=$2 ; shift ;;
            --export) rerun_option_check $# $1; EXPORT=$2 ; shift ;;
            --long) rerun_option_check $# $1; LONG=$2 ; shift ;;
            --module|-m) rerun_option_check $# $1; MODULE=$2 ; shift ;;
            --option|-o) rerun_option_check $# $1; OPTION=$2 ; shift ;;
            --required) rerun_option_check $# $1; REQUIRED=$2 ; shift ;;
            --short) rerun_option_check $# $1; SHORT=$2 ; shift ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [[ -z "$ARG" ]] && ARG="$(rerun_property_get $RERUN_MODULE_DIR/options/arg DEFAULT)"
    [[ -z "$EXPORT" ]] && EXPORT="$(rerun_property_get $RERUN_MODULE_DIR/options/export DEFAULT)"
    [[ -z "$REQUIRED" ]] && REQUIRED="$(rerun_property_get $RERUN_MODULE_DIR/options/required DEFAULT)"
    # Check required options are set
    [[ -z "$COMMAND" ]] && { echo >&2 "missing required option: --command" ; return 2 ; }
    [[ -z "$DESCRIPTION" ]] && { echo >&2 "missing required option: --description" ; return 2 ; }
    [[ -z "$MODULE" ]] && { echo >&2 "missing required option: --module" ; return 2 ; }
    [[ -z "$OPTION" ]] && { echo >&2 "missing required option: --option" ; return 2 ; }
    # If option variables are declared exportable, export them.

    # Make remaining command line options available in 
    export _CMD_LINE="$@"
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${ARG:=}
: ${COMMAND:=}
: ${DEFAULT:=}
: ${DESCRIPTION:=}
: ${EXPORT:=}
: ${LONG:=}
: ${MODULE:=}
: ${OPTION:=}
: ${REQUIRED:=}
: ${SHORT:=}
# Default command line to null if not set
: ${_CMD_LINE:=}


