# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Thu Nov  1 16:52:46 PDT 2012
#
#/ usage: stubbs:migrate  --module|-m <> 

# print USAGE and exit
rerun_option_usage() {
    grep '^#/ usage:' <"$0" | cut -c4- >&2
    return 2
}

# print SYNTAX and exit
rerun_option_error() {
    if [[ "$RERUN_COLOR" == "true" ]]
    then echo >&2 -e """SYNTAX: $*"""
    else echo >&2 "SYNTAX: $*" 
    fi
    exit 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_usage
}

# options: [module]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        --module|-m) rerun_option_check $# ; MODULE=$2 ; shift ;;
        # help option
        -?)
            rerun_option_usage
            exit 2
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT

# Check required options are set
[ -z "$MODULE" ] && { echo >&2 "missing required option: --module" ; return 2 ; }
# If option variables are declared exportable, export them.

#
return 0
