
Vagrant.configure("2") do |config|

  config.vm.box = "CentOS-6.3-x86_64-minimal"

  config.vm.synced_folder "../common/", "/tests/common"
  
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.provision :shell, :path => "test.sh", :args => "/tests/common"

end
