
Vagrant.configure("2") do |config|

  #config.vm.box_url = "https://dl.dropbox.com/u/17738575/CentOS-5.8-x86_64.box"
  #config.vm.box = "CentOS-5.8-x86_64"
  config.vm.box_url = "http://tag1consulting.com/files/centos-5.8-x86-64-minimal.box"
  config.vm.box = "centos-5.8-x86-64-minimal"

  config.vm.provision :shell, :path => "bootstrap.sh"

end
