# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Thu Sep 28 23:56:16 CDT 2017
#
#/ usage: stubbs:add-command  --command|-c <>  --description <>  --module|-m <> [ --overwrite <false>] [ --help|-?] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
#
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --command|-c) rerun_option_check $# $1; COMMAND=$2 ; shift ;;
            --description) rerun_option_check $# $1; DESCRIPTION=$2 ; shift ;;
            --module|-m) rerun_option_check $# $1; MODULE=$2 ; shift ;;
            --overwrite) rerun_option_check $# $1; OVERWRITE=$2 ; shift ;;
            --help|-?) rerun_option_usage ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [[ -z "$OVERWRITE" ]] && OVERWRITE="$(rerun_property_get $RERUN_MODULE_DIR/options/overwrite DEFAULT)"
    # Check required options are set
    [[ -z "$COMMAND" ]] && { echo >&2 "missing required option: --command" ; return 2 ; }
    [[ -z "$DESCRIPTION" ]] && { echo >&2 "missing required option: --description" ; return 2 ; }
    [[ -z "$MODULE" ]] && { echo >&2 "missing required option: --module" ; return 2 ; }
    # If option variables are declared exportable, export them.

    # Make remaining command line options available in 
    export _CMD_LINE="$@"
    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${COMMAND:=}
: ${DESCRIPTION:=}
: ${MODULE:=}
: ${OVERWRITE:=}
: ${HELP:=}
# Default command line to null if not set
: ${_CMD_LINE:=}


