# generated by add-option
# Fri Sep 16 13:42:34 PDT 2011

# print error message and exit non-zero
rerun_option_error() {
    echo "SYNTAX ERROR" >&2 ; exit 2;
}
# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_error
}

# options: [module name ovewrite template]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        -module) rerun_option_check $# ; MODULE=$2 ; shift ;;
 -name) rerun_option_check $# ; NAME=$2 ; shift ;;
 -ovewrite) rerun_option_check $# ; OVEWRITE=$2 ; shift ;;
 -template) rerun_option_check $# ; TEMPLATE=$2 ; shift ;;
        # unknown option
        -?)
            rerun_option_error
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$OVEWRITE" ] && OVEWRITE=false
[ -z "$TEMPLATE" ] && TEMPLATE=$RERUN_MODULES/stubbs/templates/default.sh
