# generated by add-command
# Fri Sep 16 13:42:34 PDT 2011
# 
#/ usage: stubbs:add-command  --command|-c <> --module|-m <> [-overwrite] [-template <>]

# print USAGE and exit
rerun_option_usage() {
    grep '^#/ usage:' <"$0" | cut -c4- >&2
    return 2
}

# print USAGE and exit
rerun_option_error() {
    if [[ "$RERUN_COLOR" == "true" ]]
    then echo -e ${red}"SYNTAX: $*"${_red} >&2 
    else echo "SYNTAX: $*" >&2
    fi
    exit 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_error
}

# options: [module name ovewrite template]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
        -m|-module) rerun_option_check $# ; MODULE=$2 ; shift ;;
 -c|-command) rerun_option_check $# ; COMMAND=$2 ; shift ;;
 -overwrite) rerun_option_check $# ; OVERWRITE=$2 ; shift ;;
 -template) rerun_option_check $# ; TEMPLATE=$2 ; shift ;;
        # unknown option
        -?)
            rerun_option_usage
            exit 2
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$OVERWRITE" ] && OVERWRITE=false
[ -z "$TEMPLATE" ] && TEMPLATE=$RERUN_MODULE_DIR/templates/default.sh
