#!/usr/bin/env python
#
#/ command: @MODULE@:@NAME@: "@DESCRIPTION@"
#
#/ usage: rerun @MODULE@:@NAME@ [options]
#
#/ rerun variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: @VARIABLES@

# Load modules
import sys
import os
sys.path.append( os.environ['RERUN_MODULE_DIR'] + "/lib" )
import functions
import options

# Parse the command options.
parser = options.parser()
options = parser.parse_args()

# ------------------------------
# Your implementation goes here.
# ------------------------------

# Done
