# generated by stubbs:add-option
# Sun Sep 25 11:26:56 PDT 2011
#
#/ usage: stubbs:docs --module|-m <>

# print USAGE and exit
rerun_option_error() {
    if [[ "$RERUN_COLOR" == "true" ]]
    then echo -e ${red}"SYNTAX: $*"${_red} >&2 
    else echo "SYNTAX: $*" >&2
    fi
    exit 2
}

# print USAGE and exit
rerun_option_usage() {
    if [ -f $0 ]
    then grep '^#/ usage:' <"$0" | cut -c4- >&2
    else echo "usage: check command for usage." >&2
    fi
    return 2
}

# check option has its argument
rerun_option_check() {
    [ "$1" -lt 2 ] && rerun_option_error
}

# options: [name]
while [ "$#" -gt 0 ]; do
    OPT="$1"
    case "$OPT" in
         -m|--module) rerun_option_check $# ; MODULE=$2 ; shift ;;
         -f|--file) rerun_option_check $# ; FILE=$2 ; shift ;;
        # unknown option
        -?)
            rerun_option_usage
            exit 2
            ;;
        # end of options, just arguments left
        *)
          break
    esac
    shift
done


# Post processes the options
[ -z "$MODULE" ] && {
    echo "Module name: "
    read MODULE
}

# If defaultable options variables are unset, set them to their DEFAULT
[ -z "$FILE" ] && FILE=$RERUN_MODULES/$MODULE/${MODULE}.1