#!/usr/bin/env bash
#
#/ command: @MODULE@:@COMMAND@: "@DESCRIPTION@"
#
#/ usage: rerun @MODULE@:@COMMAND@ [options]
#
#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option variables: @VARIABLES@

# Read module function library.
. $RERUN_MODULE_DIR/lib/functions.sh || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

# Error handling
# ---------------
# * Trap calls `rerun_die` with standard message.
# * Exit upon command errors or accessing unset variables.
#   * See [set](http://ss64.com/bash/set.html)
trap 'rerun_die $? "*** command failed: @MODULE@:@COMMAND@. ***"' ERR
set -o nounset -o pipefail

# Parse the command options.
[[ -r $RERUN_MODULE_DIR/commands/@COMMAND@/options.sh ]] && {
    . $RERUN_MODULE_DIR/commands/@COMMAND@/options.sh || rerun_die "Failed loading options parser."
    rerun_options_parse "$@"
}


# ------------------------------
# Your implementation goes here.
# ------------------------------

exit $?

# Done
